apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: build-trigger-binding
spec:
  params:
  - name: REPO_URL
    value: $(body.repository.clone_url)
  - name: BRANCH_NAME
    value: $(body.pull_request.head.sha)
  - name: IMAGE
    value: fouadhamdi/go-sample-app:2020.06.22-12.43.02
